services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ message port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "9000:9000"
    # volumes:
    #   - clickhouse_data:/var/lib/clickhouse
    #   - ./config:/etc/clickhouse-server/config.d
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "default"

# volumes:
#   clickhouse_data:
