services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: credit-svc
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
